# -*- coding: utf-8 -*-
"""TabPFN_Corrosion_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ze7KygTW_DoFPrZaGJy4CjqjCgwxuz2i

# TabPFN Aircraft Corrosion Risk Prediction
## With Corrosion Exposure Indices

This notebook implements corrosion risk prediction using TabPFN with custom corrosion exposure features.

**New Features:**
- `corrosion_exposure_index`: Combines SO2 + NO2 with humidity and parking time
- `moisture_exposure_index`: Humidity × parking time exposure

## 1. Setup and Installation
"""

# Install required packages
!pip install -q tabpfn scikit-learn pandas numpy matplotlib seaborn

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score, brier_score_loss, average_precision_score
from sklearn.preprocessing import RobustScaler
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import StratifiedKFold

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')

print("✓ Imports successful")

"""## 2. Upload Data Files

Upload the following files from your local machine:
- `corrosions_training.csv`
- `environment_training.csv`
"""

# For Google Colab
from google.colab import files

print("Upload corrosions_training.csv:")
uploaded = files.upload()

print("\nUpload environment_training.csv:")
uploaded = files.upload()

print("\n✓ Files uploaded successfully")

"""## 3. Load and Prepare Data"""

# Load corrosion data
print("Loading corrosion data...")
corr_df = pd.read_csv('corrosions_training.csv', parse_dates=['observation_date'])

# Calculate months since delivery
corr_df['months_since_delivery'] = (
    (corr_df['observation_date'].dt.year - corr_df['aircraft_delivery_year']) * 12 +
    (corr_df['observation_date'].dt.month - corr_df['aircraft_delivery_month'])
)

print(f"Corrosion data: {corr_df.shape}")
print(f"Aircraft: {corr_df['aircraft_id'].nunique()}")
print(f"Months range: {corr_df['months_since_delivery'].min():.0f} - {corr_df['months_since_delivery'].max():.0f}")

corr_df.head()

# Load environment data
print("Loading environment data...")
env_df = pd.read_csv('environment_training.csv')
env_df['month_start_date'] = pd.to_datetime(env_df['month_start_date'])

print(f"Environment data: {env_df.shape}")
print(f"\nAvailable features: {len(env_df.columns)}")

env_df.head()

"""## 4. Calculate Corrosion Exposure Indices"""

# Calculate corrosion exposure indices and advanced features
print("Calculating corrosion exposure indices and advanced features...")

# Basic corrosion exposure indices
env_df['corrosion_exposure_index'] = (
    (env_df['sulphur_dioxide_mass_mixing_ratio'] +
     env_df['nitrogen_dioxide_mass_mixing_ratio']) *
    env_df['metar_relative_humidity'] *
    env_df['total_parking_minutes'] / 1000
)

env_df['moisture_exposure_index'] = (
    env_df['metar_relative_humidity'] *
    env_df['total_parking_minutes'] / 100
)

# Bronze features: Critical exposure time
env_df['critical_exposure_time'] = (
    (env_df['total_parking_minutes'] / 60) *
    ((env_df['metar_relative_humidity'] > 60).astype(float) +
     ((env_df['metar_temperature_c'] - env_df['metar_dew_point_c']) < 3).astype(float)) / 2
)

# Silver features: Atmospheric corrosion index
env_df['atmospheric_corrosion_index'] = (
    np.log1p(env_df['sulphur_dioxide_mass_mixing_ratio'] * 1e8) * 0.3 +
    np.log1p((env_df['sea_salt_aerosol_003_05_mixing_ratio'] +
              env_df['sea_salt_aerosol_05_5_mixing_ratio'] +
              env_df['sea_salt_aerosol_5_20_mixing_ratio']) * 1e10) * 0.4 +
    (env_df['metar_relative_humidity'] / 100) * 0.3
)

# Silver features: Chemical aggressivity
env_df['chemical_aggressivity'] = (
    env_df['sulphur_dioxide_mass_mixing_ratio'] +
    env_df['nitrogen_dioxide_mass_mixing_ratio'] +
    env_df['hno3']
) * env_df['metar_relative_humidity'] / 100

print(f"\n✓ Basic indices calculated")
print(f"  Corrosion exposure index: {env_df['corrosion_exposure_index'].mean():.6f}")
print(f"  Moisture exposure index: {env_df['moisture_exposure_index'].mean():.2f}")
print(f"  Atmospheric corrosion index: {env_df['atmospheric_corrosion_index'].mean():.4f}")
print(f"  Chemical aggressivity: {env_df['chemical_aggressivity'].mean():.6f}")

"""## 5. Calculate Month Index for Environmental Data"""

# Calculate months since delivery for environmental data
# We need to merge with corr_df to get delivery dates
print("Calculating months since delivery for environmental data...")

# Get delivery dates from corrosion data
delivery_dates = corr_df[['aircraft_id', 'aircraft_delivery_year', 'aircraft_delivery_month']].drop_duplicates()

# Merge with environmental data
env_df = env_df.merge(delivery_dates, on='aircraft_id', how='left')

# Calculate months since delivery for each environmental record
env_df['months_since_delivery'] = (
    (env_df['month_start_date'].dt.year - env_df['aircraft_delivery_year']) * 12 +
    (env_df['month_start_date'].dt.month - env_df['aircraft_delivery_month'])
)

print(f"Environmental data with months_since_delivery: {env_df.shape}")
print(f"Months range: {env_df['months_since_delivery'].min():.0f} - {env_df['months_since_delivery'].max():.0f}")

# Select key environmental features (including advanced features)
env_features = [
    'metar_relative_humidity',
    'metar_temperature_c',
    'total_parking_minutes',
    'sulphur_dioxide_mass_mixing_ratio',
    'nitrogen_dioxide_mass_mixing_ratio',
    'corrosion_exposure_index',
    'moisture_exposure_index',
    'critical_exposure_time',
    'atmospheric_corrosion_index',
    'chemical_aggressivity'
]

print("✓ Environmental data prepared for time-aware aggregation")
print(f"✓ Total features to aggregate: {len(env_features)}")

"""## 6. Create Training Pairs with Time-Aware Features + Gold Features (NO DATA LEAKAGE)"""

# Create training pairs with proper temporal ordering
print("Creating training pairs with time-aware feature aggregation + Gold features...")
print("IMPORTANT: Environmental features are aggregated ONLY up to reference_month")

# Filter aircraft with sufficient observation time
valid_aircraft = corr_df[corr_df['months_since_delivery'] >= 24].copy()
print(f"Aircraft with observation >= 24 months: {len(valid_aircraft)}")

pairs = []
for idx, row in valid_aircraft.iterrows():
    aircraft_id = row['aircraft_id']
    obs_month = row['months_since_delivery']
    
    # Pair 1: Corroded state (observation month)
    # Filter environmental data up to observation month
    env_data_corroded = env_df[
        (env_df['aircraft_id'] == aircraft_id) & 
        (env_df['months_since_delivery'] <= obs_month)
    ].sort_values('months_since_delivery')
    
    if len(env_data_corroded) > 0:
        # Basic aggregations
        env_features_corroded = env_data_corroded[env_features].agg(['mean', 'std']).T
        env_features_corroded.columns = ['mean', 'std']
        env_features_corroded = env_features_corroded.fillna(0)
        
        # Gold features: cumulative and temporal
        gold_aircraft_age = len(env_data_corroded)
        gold_dose_cumulative = env_data_corroded['atmospheric_corrosion_index'].sum()
        gold_dose_acceleration = env_data_corroded['atmospheric_corrosion_index'].tail(6).sum() / (gold_dose_cumulative + 1e-6)
        gold_temp_range = env_data_corroded['metar_temperature_c'].max() - env_data_corroded['metar_temperature_c'].min()
        gold_avg_temp = env_data_corroded['metar_temperature_c'].mean()
        gold_humidity_stability = env_data_corroded['metar_relative_humidity'].std()
        gold_critical_time_cumulative = env_data_corroded['critical_exposure_time'].sum()
        gold_atm_corr_avg_24m = env_data_corroded['atmospheric_corrosion_index'].tail(24).mean()
        gold_chem_aggr_max_24m = env_data_corroded['chemical_aggressivity'].tail(24).max()
        gold_chem_aggr_max_12m = env_data_corroded['chemical_aggressivity'].tail(12).max()
        
        pair_1 = {
            'aircraft_id': aircraft_id,
            'reference_month': obs_month,
            'corrosion_risk': 1,
            'calendar_year': row['observation_date'].year,
            'gold__aircraft_age_months': gold_aircraft_age,
            'gold__dose_acceleration': gold_dose_acceleration,
            'gold__temperature_range': gold_temp_range,
            'gold__avg_temperature': gold_avg_temp,
            'gold__humidity_stability': gold_humidity_stability,
            'gold__critical_time_cumulative': gold_critical_time_cumulative,
            'gold__atm_corrosion_avg_24m': gold_atm_corr_avg_24m,
            'gold__chem_aggr_max_24m': gold_chem_aggr_max_24m,
            'gold__chem_aggr_max_12m': gold_chem_aggr_max_12m
        }
        for feat in env_features:
            pair_1[f"{feat}__mean"] = env_features_corroded.loc[feat, 'mean']
            pair_1[f"{feat}__std"] = env_features_corroded.loc[feat, 'std']
        
        pairs.append(pair_1)
    
    # Pair 2: Healthy state (24 months before)
    healthy_month = obs_month - 24
    
    # Filter environmental data up to healthy month (24 months before observation)
    env_data_healthy = env_df[
        (env_df['aircraft_id'] == aircraft_id) & 
        (env_df['months_since_delivery'] <= healthy_month)
    ].sort_values('months_since_delivery')
    
    if len(env_data_healthy) > 0:
        # Basic aggregations
        env_features_healthy = env_data_healthy[env_features].agg(['mean', 'std']).T
        env_features_healthy.columns = ['mean', 'std']
        env_features_healthy = env_features_healthy.fillna(0)
        
        # Gold features: cumulative and temporal
        gold_aircraft_age = len(env_data_healthy)
        gold_dose_cumulative = env_data_healthy['atmospheric_corrosion_index'].sum()
        gold_dose_acceleration = env_data_healthy['atmospheric_corrosion_index'].tail(6).sum() / (gold_dose_cumulative + 1e-6)
        gold_temp_range = env_data_healthy['metar_temperature_c'].max() - env_data_healthy['metar_temperature_c'].min()
        gold_avg_temp = env_data_healthy['metar_temperature_c'].mean()
        gold_humidity_stability = env_data_healthy['metar_relative_humidity'].std()
        gold_critical_time_cumulative = env_data_healthy['critical_exposure_time'].sum()
        gold_atm_corr_avg_24m = env_data_healthy['atmospheric_corrosion_index'].tail(24).mean()
        gold_chem_aggr_max_24m = env_data_healthy['chemical_aggressivity'].tail(24).max()
        gold_chem_aggr_max_12m = env_data_healthy['chemical_aggressivity'].tail(12).max()
        
        pair_0 = {
            'aircraft_id': aircraft_id,
            'reference_month': healthy_month,
            'corrosion_risk': 0,
            'calendar_year': row['observation_date'].year - 2,
            'gold__aircraft_age_months': gold_aircraft_age,
            'gold__dose_acceleration': gold_dose_acceleration,
            'gold__temperature_range': gold_temp_range,
            'gold__avg_temperature': gold_avg_temp,
            'gold__humidity_stability': gold_humidity_stability,
            'gold__critical_time_cumulative': gold_critical_time_cumulative,
            'gold__atm_corrosion_avg_24m': gold_atm_corr_avg_24m,
            'gold__chem_aggr_max_24m': gold_chem_aggr_max_24m,
            'gold__chem_aggr_max_12m': gold_chem_aggr_max_12m
        }
        for feat in env_features:
            pair_0[f"{feat}__mean"] = env_features_healthy.loc[feat, 'mean']
            pair_0[f"{feat}__std"] = env_features_healthy.loc[feat, 'std']
        
        pairs.append(pair_0)

pairs_df = pd.DataFrame(pairs)

print(f"\n✓ Created {len(pairs_df)} training samples ({len(pairs_df)//2} aircraft pairs)")
print(f"  - corrosion_risk=1: {(pairs_df['corrosion_risk']==1).sum()}")
print(f"  - corrosion_risk=0: {(pairs_df['corrosion_risk']==0).sum()}")
print(f"\n✓ Features: {len(env_features)*2} basic + 10 gold-tier = {len(env_features)*2 + 10} total")
print(f"✓ NO DATA LEAKAGE: Each pair uses only environmental data up to its reference_month")

pairs_df.head()

"""## 7. Visualize Feature Distributions"""

# Plot feature distributions
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Corrosion exposure index
axes[0, 0].hist(pairs_df['corrosion_exposure_index__mean'], bins=50, alpha=0.7, edgecolor='black')
axes[0, 0].set_title('Corrosion Exposure Index (Mean)', fontsize=12, fontweight='bold')
axes[0, 0].set_xlabel('Index Value')
axes[0, 0].set_ylabel('Frequency')

# Moisture exposure index
axes[0, 1].hist(pairs_df['moisture_exposure_index__mean'], bins=50, alpha=0.7, edgecolor='black', color='orange')
axes[0, 1].set_title('Moisture Exposure Index (Mean)', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Index Value')
axes[0, 1].set_ylabel('Frequency')

# Humidity by corrosion risk
for risk in [0, 1]:
    data = pairs_df[pairs_df['corrosion_risk'] == risk]['metar_relative_humidity__mean']
    axes[1, 0].hist(data, bins=30, alpha=0.6, label=f'Risk={risk}', edgecolor='black')
axes[1, 0].set_title('Humidity by Corrosion Risk', fontsize=12, fontweight='bold')
axes[1, 0].set_xlabel('Relative Humidity (%)')
axes[1, 0].set_ylabel('Frequency')
axes[1, 0].legend()

# Reference month distribution
axes[1, 1].hist(pairs_df['reference_month'], bins=50, alpha=0.7, edgecolor='black', color='green')
axes[1, 1].set_title('Reference Month Distribution', fontsize=12, fontweight='bold')
axes[1, 1].set_xlabel('Months Since Delivery')
axes[1, 1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""## 8. Train TabPFN Model with Cross-Validation"""

# Prepare features (including calendar_year and all gold features)
feature_cols = ['reference_month', 'calendar_year'] + [c for c in pairs_df.columns if '__' in c and c != 'aircraft_id']
X = pairs_df[feature_cols].values
y = pairs_df['corrosion_risk'].values
groups = pairs_df['aircraft_id'].values

print(f"Features: {len(feature_cols)}")
print(f"Samples: {len(X)}")
print(f"\nFeature list:")
for i, feat in enumerate(feature_cols, 1):
    print(f"  {i}. {feat}")

# Check TabPFN availability
try:
    from tabpfn import TabPFNClassifier
    import os
    os.environ["TABPFN_TOKEN"] = "tabpfn_sk_M6ludu20Be9kVMWaGFmJ2UWgHNwwPQ-gqOGXSXf15fc"
    print("✓ TabPFN available")
    use_tabpfn = True
except ImportError:
    print("⚠ TabPFN not available, using GradientBoosting fallback")
    from sklearn.ensemble import GradientBoostingClassifier
    use_tabpfn = False

# Cross-validation
from sklearn.model_selection import StratifiedGroupKFold

n_splits = 5
splitter = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=42)

aucs = []
briers = []
aps = []

print(f"Running {n_splits}-fold cross-validation...\n")

for fold, (train_idx, test_idx) in enumerate(splitter.split(X, y, groups), 1):
    print(f"Fold {fold}/{n_splits}...", end=" ")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # Scale features
    scaler = RobustScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Train model
    if use_tabpfn:
        base_model = TabPFNClassifier(device='cuda')
    else:
        base_model = GradientBoostingClassifier(
            random_state=42,
            n_estimators=200,
            max_depth=4,
            learning_rate=0.05
        )

    # Calibrate
    model = CalibratedClassifierCV(base_model, method='isotonic', cv=3)
    model.fit(X_train_scaled, y_train)

    # Predict
    y_pred = model.predict_proba(X_test_scaled)[:, 1]

    # Metrics
    auc = roc_auc_score(y_test, y_pred)
    brier = brier_score_loss(y_test, y_pred)
    ap = average_precision_score(y_test, y_pred)

    aucs.append(auc)
    briers.append(brier)
    aps.append(ap)

    print(f"AUC={auc:.4f}, Brier={brier:.4f}, AP={ap:.4f}")

print(f"\n{'='*60}")
print("CROSS-VALIDATION RESULTS:")
print(f"{'='*60}")
print(f"AUC:            {np.mean(aucs):.4f} ± {np.std(aucs):.4f}")
print(f"Brier Score:    {np.mean(briers):.4f} ± {np.std(briers):.4f}")
print(f"Avg Precision:  {np.mean(aps):.4f} ± {np.std(aps):.4f}")
print(f"{'='*60}")

"""## 9. Feature Importance Analysis"""

# Train final model for feature importance
from sklearn.ensemble import GradientBoostingClassifier

scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

model = GradientBoostingClassifier(
    random_state=42,
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05
)
model.fit(X_scaled, y)

# Get feature importance
importance_df = pd.DataFrame({
    'feature': feature_cols,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

# Plot
plt.figure(figsize=(12, 8))
plt.barh(importance_df['feature'][:15], importance_df['importance'][:15])
plt.xlabel('Importance', fontsize=12)
plt.title('Top 15 Feature Importances', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nTop 10 Features:")
print(importance_df.head(10).to_string(index=False))

"""## 10. Summary and Conclusions"""

print("="*60)
print("SUMMARY")
print("="*60)
print(f"\n✓ Dataset: {len(pairs_df)} samples from {len(valid_aircraft)} aircraft")
print(f"✓ Features: {len(feature_cols)} (including 2 new corrosion indices)")
print(f"\n✓ New Features:")
print(f"  - corrosion_exposure_index: (SO2 + NO2) × humidity × parking_time")
print(f"  - moisture_exposure_index: humidity × parking_time")
print(f"\n✓ Model Performance:")
print(f"  - AUC: {np.mean(aucs):.4f} ± {np.std(aucs):.4f}")
print(f"  - Brier Score: {np.mean(briers):.4f} ± {np.std(briers):.4f}")
print(f"  - Average Precision: {np.mean(aps):.4f} ± {np.std(aps):.4f}")
print(f"\n✓ Model: {'TabPFN' if use_tabpfn else 'GradientBoosting'} with isotonic calibration")
print("="*60)

"""# 11. Inference"""

# Upload environment_test.csv
print("Upload environment_test.csv:")
uploaded = files.upload()

print("\n✓ Test file uploaded successfully")

# Load test environment data
print("Loading test environment data...")
env_test_df = pd.read_csv('environment_test.csv')
env_test_df['month_start_date'] = pd.to_datetime(env_test_df['month_start_date'])

print(f"Test environment data: {env_test_df.shape}")
print(f"Test aircraft: {env_test_df['aircraft_id'].nunique()}")
print(f"Total rows (predictions to generate): {len(env_test_df)}")

env_test_df.head()

# Calculate corrosion exposure indices and advanced features for test data
print("Calculating corrosion exposure indices and advanced features for test data...")

# Basic corrosion exposure indices
env_test_df['corrosion_exposure_index'] = (
    (env_test_df['sulphur_dioxide_mass_mixing_ratio'] +
     env_test_df['nitrogen_dioxide_mass_mixing_ratio']) *
    env_test_df['metar_relative_humidity'] *
    env_test_df['total_parking_minutes'] / 1000
)

env_test_df['moisture_exposure_index'] = (
    env_test_df['metar_relative_humidity'] *
    env_test_df['total_parking_minutes'] / 100
)

# Bronze features: Critical exposure time
env_test_df['critical_exposure_time'] = (
    (env_test_df['total_parking_minutes'] / 60) *
    ((env_test_df['metar_relative_humidity'] > 60).astype(float) +
     ((env_test_df['metar_temperature_c'] - env_test_df['metar_dew_point_c']) < 3).astype(float)) / 2
)

# Silver features: Atmospheric corrosion index
env_test_df['atmospheric_corrosion_index'] = (
    np.log1p(env_test_df['sulphur_dioxide_mass_mixing_ratio'] * 1e8) * 0.3 +
    np.log1p((env_test_df['sea_salt_aerosol_003_05_mixing_ratio'] +
              env_test_df['sea_salt_aerosol_05_5_mixing_ratio'] +
              env_test_df['sea_salt_aerosol_5_20_mixing_ratio']) * 1e10) * 0.4 +
    (env_test_df['metar_relative_humidity'] / 100) * 0.3
)

# Silver features: Chemical aggressivity
env_test_df['chemical_aggressivity'] = (
    env_test_df['sulphur_dioxide_mass_mixing_ratio'] +
    env_test_df['nitrogen_dioxide_mass_mixing_ratio'] +
    env_test_df['hno3']
) * env_test_df['metar_relative_humidity'] / 100

print("✓ Advanced features calculated for test data")

# Get delivery dates for test aircraft
print("Getting delivery dates for test aircraft...")

# Merge delivery dates from training data
delivery_dates_test = corr_df[['aircraft_id', 'aircraft_delivery_year', 'aircraft_delivery_month']].drop_duplicates()
env_test_df = env_test_df.merge(delivery_dates_test, on='aircraft_id', how='left')

# Calculate months since delivery for test environmental data
env_test_df['months_since_delivery'] = (
    (env_test_df['month_start_date'].dt.year - env_test_df['aircraft_delivery_year']) * 12 +
    (env_test_df['month_start_date'].dt.month - env_test_df['aircraft_delivery_month'])
)

print(f"Test data with months_since_delivery: {env_test_df.shape}")

# Define the same features used in training
env_features_test = [
    'metar_relative_humidity',
    'metar_temperature_c',
    'metar_dew_point_c',
    'metar_wind_speed_kn',
    'sea_salt_aerosol_05_5_mixing_ratio',
    'sea_salt_aerosol_5_20_mixing_ratio',
    'ozone_mass_mixing_ratio',
    'sulphur_dioxide_mass_mixing_ratio',
    'nitrogen_dioxide_mass_mixing_ratio',
    'corrosion_exposure_index',
    'moisture_exposure_index'
]

# Get unique aircraft-month combinations for predictions
print("Creating time-aware test features (NO DATA LEAKAGE)...")
test_predictions = env_test_df[['aircraft_id', 'month_start_date']].drop_duplicates().reset_index(drop=True)

# For each aircraft-month, aggregate features up to that month + calculate gold features
test_rows = []
for idx, row in test_predictions.iterrows():
    aircraft_id = row['aircraft_id']
    pred_date = row['month_start_date']
    
    # Get months since delivery for this prediction
    aircraft_data = env_test_df[env_test_df['aircraft_id'] == aircraft_id].iloc[0]
    pred_month = (
        (pred_date.year - aircraft_data['aircraft_delivery_year']) * 12 +
        (pred_date.month - aircraft_data['aircraft_delivery_month'])
    )
    
    # Filter environmental data up to prediction month
    env_data_pred = env_test_df[
        (env_test_df['aircraft_id'] == aircraft_id) & 
        (env_test_df['months_since_delivery'] <= pred_month)
    ].sort_values('months_since_delivery')
    
    if len(env_data_pred) > 0:
        # Basic aggregations
        env_features_agg = env_data_pred[env_features_test].agg(['mean', 'std']).T
        env_features_agg.columns = ['mean', 'std']
        env_features_agg = env_features_agg.fillna(0)
        
        # Gold features: cumulative and temporal (matching training)
        gold_aircraft_age = len(env_data_pred)
        gold_dose_cumulative = env_data_pred['atmospheric_corrosion_index'].sum()
        gold_dose_acceleration = env_data_pred['atmospheric_corrosion_index'].tail(6).sum() / (gold_dose_cumulative + 1e-6)
        gold_temp_range = env_data_pred['metar_temperature_c'].max() - env_data_pred['metar_temperature_c'].min()
        gold_avg_temp = env_data_pred['metar_temperature_c'].mean()
        gold_humidity_stability = env_data_pred['metar_relative_humidity'].std()
        gold_critical_time_cumulative = env_data_pred['critical_exposure_time'].sum()
        gold_atm_corr_avg_24m = env_data_pred['atmospheric_corrosion_index'].tail(24).mean()
        gold_chem_aggr_max_24m = env_data_pred['chemical_aggressivity'].tail(24).max()
        gold_chem_aggr_max_12m = env_data_pred['chemical_aggressivity'].tail(12).max()
        
        test_row = {
            'aircraft_id': aircraft_id,
            'month_start_date': pred_date,
            'reference_month': pred_month,
            'calendar_year': pred_date.year,
            'gold__aircraft_age_months': gold_aircraft_age,
            'gold__dose_acceleration': gold_dose_acceleration,
            'gold__temperature_range': gold_temp_range,
            'gold__avg_temperature': gold_avg_temp,
            'gold__humidity_stability': gold_humidity_stability,
            'gold__critical_time_cumulative': gold_critical_time_cumulative,
            'gold__atm_corrosion_avg_24m': gold_atm_corr_avg_24m,
            'gold__chem_aggr_max_24m': gold_chem_aggr_max_24m,
            'gold__chem_aggr_max_12m': gold_chem_aggr_max_12m
        }
        for feat in env_features_test:
            test_row[f"{feat}__mean"] = env_features_agg.loc[feat, 'mean']
            test_row[f"{feat}__std"] = env_features_agg.loc[feat, 'std']
        
        test_rows.append(test_row)

test_agg = pd.DataFrame(test_rows)

print(f"✓ Aggregated test features: {test_agg.shape}")
print(f"✓ Total predictions to generate: {len(test_agg)}")
print(f"✓ NO DATA LEAKAGE: Each prediction uses only environmental data up to its reference_month")

test_agg.head()

# Create id column in format: aircraft_id_YYYY-MM
test_agg['id'] = (
    test_agg['aircraft_id'] + '_' +
    test_agg['month_start_date'].dt.strftime('%Y-%m')
)

print(f"✓ Reference months calculated")
print(f"Reference month range: {test_agg['reference_month'].min():.0f} to {test_agg['reference_month'].max():.0f}")

test_agg.head()

# Train final model on all training data
print("Training final model on all training data...")

scaler_final = RobustScaler()
X_train_final = scaler_final.fit_transform(X)

if use_tabpfn:
    base_model_final = TabPFNClassifier(device='cuda')
else:
    base_model_final = GradientBoostingClassifier(
        random_state=42,
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05
    )

model_final = CalibratedClassifierCV(base_model_final, method='isotonic', cv=3)
model_final.fit(X_train_final, y)

print("✓ Final model trained")

# Prepare test features for ALL predictions
print("Preparing test features for all rows...")

# Build feature matrix matching training structure
X_test_values = []

# reference_month
X_test_values.append(test_agg['reference_month'].values)

# Environmental features - match training feature order
for feat in feature_cols[1:]:  # Skip reference_month
    # Extract base feature name (remove __mean or __std suffix)
    base_feat = feat.replace('__mean', '').replace('__std', '')

    if base_feat in test_agg.columns:
        X_test_values.append(test_agg[base_feat].values)
    else:
        print(f"  WARNING: Missing feature {feat}, using zeros")
        X_test_values.append(np.zeros(len(test_agg)))

X_test = np.column_stack(X_test_values)

# Handle any NaN values
X_test = np.nan_to_num(X_test, nan=0.0)

print(f"Test samples prepared: {len(X_test)}")
print(f"Feature shape: {X_test.shape}")

# Scale test features
X_test_scaled = scaler_final.transform(X_test)

# Predict probabilities for ALL rows
print("Making predictions for all rows...")
y_pred_proba = model_final.predict_proba(X_test_scaled)[:, 1]

# Clip to valid range
y_pred_proba = np.clip(y_pred_proba, 1e-6, 1 - 1e-6)

# Create submission dataframe
submission_df = pd.DataFrame({
    'id': test_agg['id'],
    'corrosion_risk': y_pred_proba
})

print(f"\n✓ Predictions complete!")
print(f"Total predictions: {len(submission_df)}")
print(f"Unique aircraft: {test_agg['aircraft_id'].nunique()}")
print(f"\nPrediction statistics:")
print(f"  Min:  {y_pred_proba.min():.4f}")
print(f"  Max:  {y_pred_proba.max():.4f}")
print(f"  Mean: {y_pred_proba.mean():.4f}")
print(f"  Median: {np.median(y_pred_proba):.4f}")
print(f"  Std:  {y_pred_proba.std():.4f}")

submission_df.head(10)

# Visualize prediction distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram
axes[0].hist(y_pred_proba, bins=50, alpha=0.7, edgecolor='black', color='steelblue')
axes[0].set_title('Distribution of Predicted Corrosion Risk', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Predicted Probability')
axes[0].set_ylabel('Frequency')
axes[0].axvline(y_pred_proba.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {y_pred_proba.mean():.3f}')
axes[0].legend()

# Cumulative distribution
sorted_probs = np.sort(y_pred_proba)
cumulative = np.arange(1, len(sorted_probs) + 1) / len(sorted_probs)
axes[1].plot(sorted_probs, cumulative, linewidth=2, color='darkorange')
axes[1].set_title('Cumulative Distribution of Predictions', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Predicted Probability')
axes[1].set_ylabel('Cumulative Proportion')
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Save submission file
submission_df.to_csv('submission.csv', index=False)

print("✓ Submission file saved as 'submission.csv'")
print(f"\nSubmission format:")
print(submission_df.head())
print(f"\nLast predictions:")
print(submission_df.tail())

# Download file (for Colab)
files.download('submission.csv')

print("="*60)
print("INFERENCE COMPLETE")
print("="*60)
print(f"\n✓ Test aircraft processed: {len(submission_df)}")
print(f"✓ Predictions generated using reference month: {reference_month_test:.0f}")
print(f"✓ Model: {'TabPFN' if use_tabpfn else 'GradientBoosting'} with isotonic calibration")
print(f"\n✓ Submission file: submission.csv")
print(f"  - Format: aircraft_id, corrosion_risk")
print(f"  - Rows: {len(submission_df)}")
print(f"\n✓ Prediction range: [{y_pred_proba.min():.4f}, {y_pred_proba.max():.4f}]")
print(f"✓ Mean prediction: {y_pred_proba.mean():.4f}")
print("="*60)

